# Generated by Django 4.1.7 on 2023-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
